GET http://localhost:8000/api/products/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTg5NTc1LCJpYXQiOjE3Mzc5ODkyNzUsImp0aSI6IjAwYjBmMDZjOWRkYjQ0MjFhMmQyY2QxYzgwZGM1NmRlIiwidXNlcl9pZCI6MX0.6nZKQTdM5rcqlu9DMc69VAw6jAQZjOvPBiaobW2tieU

###

POST http://localhost:8000/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTg5NjI5LCJpYXQiOjE3Mzc5ODkzMjksImp0aSI6IjM2Y2VjNDgyNGE4OTQ0ZGFhNDFhMTMwN2Q2MDgwYjdlIiwidXNlcl9pZCI6MX0.LuMr-jXyeBScXZUiqeqTqH55f9pNA2rTozeK0mrSQ6k

{
    "name": "Nike Hypervenom 2018",
    "price": -1.00,
    "stock": 15,
    "description": "Nike Boots from Rusia 2018 FIFA World Cup"
}

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "pedro",
    "password": "fef51e5a"
}

###
GET http://localhost:8000/api/user_orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3OTA4NTgxLCJpYXQiOjE3Mzc5MDgyODEsImp0aSI6ImZhMzY5OGU4NDQyYzQwMTdiYjU1OWQ3MmI2MjgyNDdkIiwidXNlcl9pZCI6MX0.zAt-tmZzNy1_P-h3tu4y6lxdNcmIz4TfFNdgdYAujF8
###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzkyNTIyNiwiaWF0IjoxNzM3ODM4ODI2LCJqdGkiOiIxYzFiM2E4NWJkNTA0NDAxOGZhODM2ZjYwZWE5NTNmMSIsInVzZXJfaWQiOjF9.FlF45qF12ZN53YjnMwt6bgAhpGX1prLbl3h1UFmvimo"
}

###

PUT http://localhost:8000/api/products/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3ODUwNTAxLCJpYXQiOjE3Mzc4NTAyMDEsImp0aSI6IjU3ZTQzNjUzMGU3YzQwNWZhYWRlNTU5ODQ1OTljNTMxIiwidXNlcl9pZCI6MX0.Jv2TJFj1gEECgOD-thG8fBBDH-BFUQ4R1m9-sciod0o
